export const METHOD_LABELS: Record<string, string> = {
  tribute: 'Tribute',
  cryptobot: 'CryptoBot',
  heleket: 'Heleket',
  yookassa: 'YooKassa',
  mulenpay: 'MulenPay',
  pal24: 'PayPalych',
  platega: 'Platega',
  wata: 'WATA',
  freekassa: 'Freekassa',
  freekassa_sbp: 'Freekassa СБП',
  freekassa_card: 'Freekassa Карта',
  cloudpayments: 'CloudPayments',
  kassa_ai: 'Kassa AI',
  riopay: 'RioPay',
  severpay: 'SeverPay',
  manual: 'Ручное пополнение',
};
